### ISSUE TITLE
List Nuxt3 install instructions in readme

### ISSUE THREAD

**Issue by polyclick** [AndreSouzaAbreu/vue-data-table#105]
Hi

Would be great to put the install instructions for with nuxt3 in the readme. Took me a bit to figure it out ;)

- Create file: `/plugins/VueDataTable.plugin.ts`
- Use following code to register the plugin

```
// plugins/VueDataTable.plugin.ts
import { defineNuxtPlugin } from '#app'
import VueDataTable from '@uwlajs/vue-data-table'
import '@uwlajs/vue-data-table/dist/style.css'

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.vueApp.use(VueDataTable)
})
```

Nuxt3 will register the component automatically, with the default styling. 
Use it with tag: `<vue-data-table></vue-data-table>`

Cheers!

**Comment by uwla** [comment]
this is useful indeed. I'll add it to the documentation, so Nuxt users won't have to figure it out

**Comment by uwla** [comment]
Thanks for the suggestion, the docs was updated to include nuxt instructions.
