### ISSUE TITLE
HTML in data / table cell

### ISSUE THREAD

**Issue by Waterdhavian** [AndreSouzaAbreu/vue-data-table#22]
I was wondering if there is a way to render HTML inside the table when that HTML is present in the data served to the Vue DataTable.

I saw in demo 2 that for version 2 of this plugin you had actions that were HTML buttons.
This is my current configuration:

`return {
                columns: [
                    {
                        key: "name",
                        title: 'Name'
                    },
                    {
                        key: "id",
                        title: 'Relation ID'
                    },
                    {
                        key: "actions",
                        title: 'Actions',
                        sortable: false
                    },
                ],
                data: this.data,
                showPagination: false,
                defaultPerPage: 50,
                showEntriesInfo: false,
                showPerPage: false,
                showDownloadButton: false,
            }`

 this.data has objects that contains HTML to show actions (2 anchors that link to another page, which is now shown as text instead of clickable links.

Is it possible to add a property to a column say: html: true and if enabled it will render HTML found in the string as HTML instead of showing the code as text.

**Comment by Waterdhavian** [comment]
I solved it by using a custom component for that one cell instead.

**Comment by AndreSouzaAbreu** [comment]
> I was wondering if there is a way to render HTML inside the table when that HTML is present in the data served to the Vue DataTable.
> 
> I saw in demo 2 that for version 2 of this plugin you had actions that were HTML buttons.
> This is my current configuration:
> 
> `return { columns: [ { key: "name", title: 'Name' }, { key: "id", title: 'Relation ID' }, { key: "actions", title: 'Actions', sortable: false }, ], data: this.data, showPagination: false, defaultPerPage: 50, showEntriesInfo: false, showPerPage: false, showDownloadButton: false, }`
> 
> this.data has objects that contains HTML to show actions (2 anchors that link to another page, which is now shown as text instead of clickable links.
> 
> Is it possible to add a property to a column say: html: true and if enabled it will render HTML found in the string as HTML instead of showing the code as text.

Yes, it was possible to render HTML in version 2. The prop was called `unsafeHTML`. If set to `true`, it would render HTML. See this issue https://github.com/AndreSouzaAbreu/vue-data-table/issues/4.

But I disabled that prop for security reasons and now I let the user provide a custom component, which adds more flexibility. Good that you were able to solve it!
