### ISSUE TITLE
how to add one footer row static 

### ISSUE THREAD

**Issue by abdulcrb** [AndreSouzaAbreu/vue-data-table#25]
how to add one footer row static for fill in the total number of column contents like total price, total sum,
thx

**Comment by AndreSouzaAbreu** [comment]
It is not possible yet, but I will surely add functionality to do it because it is a fantastic feature. Thanks

**Comment by abdulcrb** [comment]
thx for your replay

**Comment by AndreSouzaAbreu** [comment]
Done :)
