### ISSUE TITLE
Customizing configurations not working

### ISSUE THREAD

**Issue by ikubij** [AndreSouzaAbreu/vue-data-table#3]
Let me be the first to leave an issue. I really love what you are doing, especially leaving jQuery out of it.

My issue: Most customizing configurations are not working, especially those at the bottom, cannot change :showExportButton, infoText, previousButtonText, nextButtonText.

Also, it would be great if I could specify position, for example if I could place the showing entries at the bottom.

Kudos, continue working on this great project

**Comment by AndreSouzaAbreu** [comment]
Hi!

About customizing the buttons, that should be working.
Here is a sample of what you can do:

``vue
<template>
    <data-table  v-bind="bindings" >
</template>

<script>
export default {
   name: "TableDashboard",
   computed: {
        bindings: {
            return {
                data: [/*here goes the data*/],
                columns: [/*here goes the columns*/],
                showDownloadButton: false, // previously, it was showExportButton, but it changed from last release
                text: {
                    infoText: "Your text",
                    previousButtonText: "Custom Text",
                    nextButtonText: "Custo
                }
            }
        }
    }
}
</script>
``

The showExportButton is actually showDownloadButton. It was probably my mistake who forgot to update this in README.me.
Actually, I have to change this because it shoulld be showExportData to match the component ExportData.vue

About changing the position of showEntries, that is a good idea! I will try to think about how to do this in the next week or so.

Let me know if you solved the problem of customizing text.

**Comment by AndreSouzaAbreu** [comment]
Hello, can you give me some feedback ? How did it goes?

**Comment by AndreSouzaAbreu** [comment]
Hello!

I'm glad to announce that from now on, version 2.2.2 of VueDataTable, we have the option to set a custom order of components!! 

For example, to place the "showing entries" at bottom, you may include the following scss

```scss
	.data-table {
		display: grid;
		width: 100%;
		grid-template-columns: 25% 25% 25% 25%;
	
		& > .data-table-search-filter, .data-table-pagination, .data-table-per-page {
			margin-left: auto
		}
		
		& > .data-table-export-data {
			margin-left: 0;

			select {
				max-width: 70px;
			}
		}
	
		@media (min-width: 1401px) {
			grid-template-areas:
				"download download search search"
				"table table table table"
				"info pagination pagination perPage";
		}
	
		@media (min-width: 1051px) AND (max-width: 1400px) {
			grid-template-areas:
				"download download search search"
				"table table table table"
				"info pagination pagination pagination"
				". . . perPage";
		}
	
		@media (min-width: 851px) AND (max-width: 1050px) {
			grid-template-areas:
				"download download search search"
				"table table table table"
				"pagination pagination pagination pagination"
				"info info perPage perPage";
		}
	
		@media (max-width: 800px) {
			& > .data-table-pagination {
				flex-wrap: wrap;
			}
		}
	
		@media (min-width: 651px) AND (max-width: 850px) {
			grid-template-areas:
				"download download search search"
				"table table table table"
				"pagination pagination pagination pagination"
				"info info info info"
				"perPage perPage perPage perPage";
		}
	
		@media (max-width: 650px) {
			grid-template-areas:
				"search search search search"
				"download download download download "
				"table table table table"
				"pagination pagination pagination pagination"
				"info info info info"
				"perPage perPage perPage perPage";
	
			& > .data-table-export-data {
				margin-left: auto
			}
		}
	
	
		&> div {
			margin-top: 1rem;
			max-width: 100%;
		}
	}
```

I have tested it and it worked!
