### ISSUE TITLE
Download as xls, csv, json doesn't work properly

### ISSUE THREAD

**Issue by tannguyencse19** [AndreSouzaAbreu/vue-data-table#30]
Hey, your product is so awesome. Thanks!

In the app demo [https://ygnl5.csb.app/](url), I can download all the type. But when I copy your code from demo and try to download, it appears like this.

![image](https://user-images.githubusercontent.com/62830718/133335804-ba250cd6-50b2-4102-9aae-4e385a66b287.png)

I try with txt and it works fine.

Any suggestion?

**Comment by AndreSouzaAbreu** [comment]
I can confirm the bug. I don't know why it's working only on the demo app. I'll try to fix it soon

**Comment by moazzaq** [comment]
How can I hide the download buttons until the problem is solved?
