### ISSUE TITLE
Suggest to add loading state

### ISSUE THREAD

**Issue by macoycorpuz** [AndreSouzaAbreu/vue-data-table#34]
Hi! Adding a loading state and loading text would be nice

**Comment by Asinging** [comment]
Especially when requesting a for more record from the server, there should be a visual loading state telling the user for that a that table is expecting records from the server when it hits 'isLastPage' during pagination

**Comment by AndreSouzaAbreu** [comment]
> Especially when requesting more records from the server, there should be a
> visual loading state telling the user that the table is expecting records
> from the server when the table hits 'isLastPage' during pagination

Can you explain it better? In your opinion, what should happen if there are
already data on the table and the user is in the last page, but there is still
more data to load?

**Comment by Asinging** [comment]
sorry for late replies, i wanted to get in contact with you personally @AndreSouzaAbreu , the datatable already expose a property named "isLastPage". in my implemenation now, whenever this property resolves to true i send another query to the server to fetch more record. but the user is left in the dark as whether the request  is processing or not, to solve this issues, i suggest the datatable should have a vue named slot, where one can reference and add a loader when a request for more record is  sent for user experience.

**Comment by Asinging** [comment]
for the loader stuff may something like this or even any loader equivalent
https://datatables.net/examples/server_side/simple.html

**Comment by AndreSouzaAbreu** [comment]
Hi! It is now possible to add custom component for loading state :)

Check out the latest version of this plugin !

**Comment by Asinging** [comment]
> Hi! It is now possible to add custom component for loading state :)
> 
> Check out the latest version of this plugin !

great works

**Comment by macoycorpuz** [comment]
Great work! Happy to try the feature 😊
