### ISSUE TITLE
Download Search Or Filtered Result Data on Table

### ISSUE THREAD

**Issue by z41dth3c0d3r** [AndreSouzaAbreu/vue-data-table#41]
Let's say i have 100 products data loaded in to vue-data-table. Now i am sorting products by price and table will change right? from initial table data to sorted by price data right? If i download now than It will give me initial data not sorted by price data! So how can i download those sorted by price data!

**Comment by AndreSouzaAbreu** [comment]
Oh, this should not be happening! You are right, it should downloaded the data filtered and sorted by price!
I think this will be easy to fix. I plan to get it fixed in the next week, which I'll have some free time

**Comment by z41dth3c0d3r** [comment]
Okay got it!

**Comment by AndreSouzaAbreu** [comment]
fixed

**Comment by z41dth3c0d3r** [comment]
Thank you so much for the fix, consideration and your time!!!
