### ISSUE TITLE
Sorting gives problems with integer columns and how can I align the cell titles?

### ISSUE THREAD

**Issue by mendozajoser** [AndreSouzaAbreu/vue-data-table#46]

**Comment by AndreSouzaAbreu** [comment]
Hello.

By default, the columns are sorted as strings. If you want to sort numeric
columns, then you must change the type of the column as follows:

```javascript
columns: [
    { key: "price", type: "number" },
    /* default type is already string if you don't specify */
    { key: "product" },
    { key: "vendor" },
    /**/
]
```

To align cell titles, use CSS:

```css
th {
    text-align: center;
}
```

If that doesn't work, try adding `!important`, or applying more specific CSS
rules.

**Comment by mendozajoser** [comment]
Thanks my friend, the sorting worked perfectly, now the align, yes I know that option but I was referring more to individually, I want some that are centered, others at the beginning and others at the end

**Comment by AndreSouzaAbreu** [comment]
Hello! So, about aligning cells individually, it is possible to do that
with custom CSS (this plugin doesn't by itself provide a way for that).

Here is how:

```
tr > th + th + th, tr > td+td+td {
    text-align: center
}
```

This will center the text of the third column.

**Comment by mendozajoser** [comment]
Thanks my friend
