### ISSUE TITLE
How I add customize Column like S.No

### ISSUE THREAD

**Issue by Siva-Leo** [AndreSouzaAbreu/vue-data-table#5]
i tried like
     ```
{
            key:'index',
            title:'S.No',
            sortable: false,
       },
```
Expected behaviour
 To display the ### S.No column and if i'm in search the ### S.No value must be rearrange

**Comment by AndreSouzaAbreu** [comment]
Hello!

Why is there a hashtag # in your code? If you use hashtags like that it won't work in JS.

If you remove the hashtags hopefully it should work.

Lemmy know how it goes

**Comment by AndreSouzaAbreu** [comment]
Hi! Can you give me an update? Did you solve the problem?

**Comment by Siva-Leo** [comment]
I think hashtag this my typing mistake...

**Comment by Siva-Leo** [comment]
My object does not have index key. But i want display the series of row number. how i do that

**Comment by AndreSouzaAbreu** [comment]
You can add a key to your object if it does not have one. For example
```javascript
let myObjects = [ /* an array of objects*/]
myObjects.forEach((object, index) => object.index = index) // this line loops through each object and adds the index key of the object.
console.log("the key is ", myObjects[2].index) // should log  "the key is 2"
```

**Comment by Siva-Leo** [comment]
I already do like that and achieved.i just want know plugin have any default option. Thanks for your attention.
