### ISSUE TITLE
Question: Is it possible to display all the in the console?

### ISSUE THREAD

**Issue by paul-cylix** [AndreSouzaAbreu/vue-data-table#55]
Hi i am trying to select or display all of the data in the current page.
i want to display all the row data that are in page 1 to console is it possible?

**Comment by AndreSouzaAbreu** [comment]
> i want to display all the row data that are in page 1 to console is it possible?

This is actually possible, but the plugin wasn't designed for this; it just
happened that accidentaly there is a way for you do that thanks to the footer
component feature.

You just have to use a custom footer component (even if you don't need it, you
are required to use it if you want to print the data of current page to
console). Then, what you have to do is this:

```javascript
<template>
  <tfoot style="display: 0"></tfoot>  
</template>
<script>
export default {
  name: "TableFooter",
  methods: {
    logData() {
      console.log(this.dataDisplayed);
    }
  },
  watch: {
    dataDisplayed: {
      immediate: true,
      handler: 'logData'
    }
  },
  props: {
    data: Array,
    dataDisplayed: Array,
    dataFiltered: Array,
  }
}
</script>
```

**Comment by paul-cylix** [comment]
thank you sir. this works for me you are the best
