### ISSUE TITLE
how to add new lang and set it globaly for all datatables

### ISSUE THREAD

**Issue by Coder0010** [AndreSouzaAbreu/vue-data-table#6]
..

**Comment by AndreSouzaAbreu** [comment]
sorry, this is not possible yet. I will work on to add this new feature. It will probably be available in a couple of weeks

**Comment by Coder0010** [comment]
Wating for it 
and thanks for response 👍 

> sorry, this is not possible yet. I will work on to add this new feature. It will probably be available in a couple of weeks

**Comment by AndreSouzaAbreu** [comment]
Hello @Coder0010 ! 
This feature is finally available! Now you can add custom languages and use it on any instance of VueDataTable.
Here is an example from the docs


```javascript
import { languageServiceProvider } from "@andresouzaabreu/vue-data-table";
const loremIpsumLanguage = {
    perPageText: "lorem ppsum",
    nextButtonText: "labore nostrud",
    /* more text ... */
};
languageServiceProvider.setLang("lorem", loremIpsumLanguage)

/**
 * @function setLang
 * @param {String} lang           the name of the language
 * @param {Object} translations   an object with the translated text
*/
```

Sorry it took too long to add this feature. I was busy last year, but finally got some free time to work on that.
