### ISSUE TITLE
Action button doesn't show

### ISSUE THREAD

**Issue by careerdimasprayoga** [AndreSouzaAbreu/vue-data-table#62]
I'am using vue version 2.6.12. I've already follow the code example on demo 1 and make sure that included ```actionMode: "single"```. How to show the action button or using template inside table like bootstrap table ?

**Comment by AndreSouzaAbreu** [comment]
Are you using the correct version of this package? Support for action buttons
(like in demo 1) has been replaced by custom components.

You can provide a custom Vue Component to be displayed in the table cell, which
you can use to show buttons or whatever you want. Please, see the Custom Component
section on the README. There issues similar to yours which have been addressed.
You may want to check out these too.
