### ISSUE TITLE
Custom Component

### ISSUE THREAD

**Issue by Siddhesh220398** [AndreSouzaAbreu/vue-data-table#99]
When Custom Componet is Add i.e. Footer Component but ican't display. As per your code add but not reflect

`<template>
	<div>
		<data-table v-bind="parameters" @actionTriggered="handleAction" />
	</div>
</template>

<script>
import ImageTable from './ImageTable.vue';
import statusBadge from './statusBadge.vue';
import TableFooter from './TableFooter.vue'
export default {
	name: 'TableDefault',
	props: {
		tableData: {
			type: Array,
			required: true
		},
        is_search: {
			type: Boolean,
			required: true
		},
		showAction:{
			type:Boolean,
			required:false,
			default:false
		},
		columns:{
                required:false,
                type:Array,
                default:function(){
                    return 	[
						{
							key: 'project',
							title: 'Project',
							sortable: false,
							component: ImageTable,

						},
						{
							key: 'funding',
							title: 'Your Funding',
							sortable: false,
						},
						{
							key: 'date',
							title: 'Funding Date',
							sortable: false,
						},
						{
							key: 'status',
							title: 'Project Status',
							sortable: false,
							component: statusBadge,
						}
					];
                }
            },
	},
	data() {
		return {
		};
	},
	components: {},
	computed: {
		parameters() {

			return {
				// data: [], // pass the empty array to see message
				data: this.tableData,
				lang: 'en',
				actionMode: 'single',
				perPageSizes: [5, 25, 50, 100],
				defaultPerPage: 5,
				showPerPage: false,
				showEntriesInfo: false,
				showSearchFilter: this.is_search,
				showDownloadButton: false,
				tableClass: 'table table-default table-hover table-borderless',
				columns: this.columns,
                footerComponent: TableFooter,
			};
		},
	},

	methods: {
		handleAction(action, payload) {
			window.alert('check out the console to see the data logged');
		}
	},
};
</script>
<style lang="scss">
@import '../assets/scss/components/table.scss';
</style>
`

**Comment by uwla** [comment]
Hi. I believe this may be an issue with how Vue3 handles dynamic components with `<component :is=dynamicComponent />`.

I faced this issue and the **best** way to solve it, without getting a lot of warnings from Vue, is to register the component globally and pass the component name as string:

```javascript
import App from './App'
import { StatusBadge } from './components'
const app = createApp(App);
app.component('status-badge', StatusBadge);

// later on
columns = [
  /**/
  { title: 'Project Status', component: 'status-badge' }
]
```

By the way, you do not need to pass `key` if you are using a custom component. The key is ignored. Also, by default, columns that use custom components are not sortable unless a user-provided sorting function is passed.
